### ISSUE TITLE
Add extra test case?

### ISSUE THREAD

**Issue by ckesurf** [learn-co-curriculum/find-first-duplicate#3]
### Canvas Link

https://learning.flatironschool.com/courses/4997/assignments/165451?module_item_id=357010

### Concern

Could we clarify, in both the README and the test cases, that the duplicates don't have to be next to each other? 

For example, I was thinking, After this [test](https://github.com/learn-co-curriculum/find-first-duplicate/blob/master/javascript/tests/find_first_duplicate.test.js#L11-L16),

```
expect(findFirstDuplicate([1, 2, 3, 3, 2, 1])).toBe(3);
```

We could add another

```
expect(findFirstDuplicate([1, 2, 3, 4, 2, 3, 1])).toBe(2);
```
This test case communicates that 1) duplicates don't have to be next to each other, and 2) when there are multiple duplicates, such as 2s and 3s, the first one is the desired result (2, in this case). 

This is all, of course, assuming that I have read and interpreted this assignment correctly, of course.

**Comment by lizbur10** [comment]
Hi @ckesurf  - nice addition! The new test has been added. 

Thanks for contributing to the Flatiron School curriculum 💙
